#!/bin/sh
# gen-syscall-names.sh — emit the syscall NAME list the asmspy syscall view
# decodes against, taken from the COMPILING HOST's own <sys/syscall.h>.
#
# Names only, never numbers: asmspy_engine.c expands each through
# `[__NR_<name>] = "<name>"`, so the compiler supplies the number from the same
# headers it compiles against. A hand-maintained table would drift as the kernel
# grows syscalls (and would break wherever a __NR_ this file names is absent);
# this cannot.
set -eu
CC="${CC:-cc}"

out=$(echo '#include <sys/syscall.h>' | "$CC" -E -dM - |
    awk '/^#define __NR_[a-z_0-9]+ /{ print "SC(" substr($2, 6) ")" }' | sort)

# A silently-empty table would degrade every syscall to "syscall#N" with no
# other symptom, so make a broken toolchain/header set a hard build error.
[ -n "$out" ] || {
    echo "gen-syscall-names.sh: no __NR_* macros from $CC <sys/syscall.h>" >&2
    exit 1
}

echo "/* generated by cli/gen-syscall-names.sh — do not edit */"
printf '%s\n' "$out"
