// test_loom_golden.cpp — the committed golden looms, replayed end to end
// (05-loom-day-one.md T7 step 3). Render-only, and that is the point: these
// fixtures reach the fabric through 02's reader and 03's document model, with
// no engine anywhere on the link line.
//
// The four fixtures are generated by `make asmtrace-golden`
// (tools/asmtrace_record.c) and byte-stable — `make asmtrace-golden-check`
// fails as a byte diff if a field order or a recorded value moves.
#include <algorithm>
#include <cstdio>
#include <string>
#include <vector>

#include "loom/annex.h"
#include "loom/fabric_plan.h"
#include "loom/feed.h"
#include "loom/lineage.h"

#ifndef ASMTEST_GOLDEN_DIR
#error "ASMTEST_GOLDEN_DIR must be defined by the build (mk/desktop.mk)"
#endif

using namespace asmdesk;

static int failures;
static void fail(const std::string &what, const std::string &why) {
    std::fprintf(stderr, "FAIL %s: %s\n", what.c_str(), why.c_str());
    failures++;
}
static void check(const std::string &what, bool cond, const std::string &why) {
    if (!cond)
        fail(what, why);
}

struct Loaded {
    loom_feed_t feed;
    loom_fabric_t fabric;
    bool ok = false;
};

static Loaded load(const std::string &name) {
    Loaded L;
    std::string path = std::string(ASMTEST_GOLDEN_DIR) + "/" + name;
    std::string err;
    auto rec = load_recording_file(path, err);
    if (!rec) {
        fail("load " + name, err);
        return L;
    }
    Streams s = decode_streams(*rec);
    if (!loom_fabric_from_streams(s, &L.feed, &L.fabric, &err)) {
        fail("weave " + name, err);
        return L;
    }
    L.ok = true;
    return L;
}

static int lane_named(const loom_fabric_t &f, const char *n) {
    for (size_t i = 0; i < f.lanes.size(); i++)
        if (f.lanes[i].name == n)
            return static_cast<int>(i);
    return -1;
}
static int band_lane(const loom_fabric_t &f) {
    for (size_t i = 0; i < f.lanes.size(); i++)
        if (f.lanes[i].kind == loom_lane_kind::mem_band)
            return static_cast<int>(i);
    return -1;
}
static loom_view_t wide() {
    loom_view_t v;
    v.steps_per_px = 0.05;
    v.px_w = 800;
    v.px_h = 400;
    v.lane_h = 18;
    return v;
}
static size_t count(const std::vector<loom_prim_t> &p, loom_prim k) {
    size_t n = 0;
    for (const loom_prim_t &x : p)
        if (x.kind == k)
            n++;
    return n;
}

int main() {
    std::vector<loom_prim_t> prims;

    // ---------------------------------------------------------------------
    // loom-df-chain — walkthrough #1, hand-derivable on paper.
    // ---------------------------------------------------------------------
    {
        Loaded L = load("loom-df-chain.asmtrace");
        if (!L.ok)
            return 1;
        const loom_fabric_t &f = L.fabric;
        check("df-chain has 6 steps", f.steps == 6,
              "got " + std::to_string(f.steps));

        // Deck order, from the producer's own tables.
        const char *deck[] = {"rdi", "rsi", "rdx", "rcx", "rax", "rsp"};
        int prev = -1;
        for (const char *n : deck) {
            int at = lane_named(f, n);
            check(std::string("df-chain deck has ") + n, at >= 0, "");
            check(std::string("df-chain deck order ") + n, at > prev, "");
            prev = at;
        }
        const int band = band_lane(f);
        check("df-chain has exactly one stack band", band >= 0,
              loom_fabric_dump(f));

        // The store's chip and the load-after-store hop.
        bool chip7 = false;
        for (const loom_span_t &s : f.spans)
            if (static_cast<int>(s.lane) == band && s.t_write == 1)
                chip7 = s.value_valid && s.value == 7;
        check("df-chain: the step-1 store carries chip 7", chip7,
              loom_fabric_dump(f));

        bool hop12 = false;
        for (const loom_hop_t &h : f.hops) {
            const asmtest_defuse_edge_t &e = L.feed.edges[h.edge];
            if (e.from_step == 1 && e.to_step == 2 &&
                static_cast<int>(f.spans[h.from_span].lane) == band)
                hop12 = true;
        }
        check("df-chain: the 1 -> 2 load-after-store hop is on the band", hop12,
              loom_fabric_dump(f));

        // rax is written last at step 4 and nothing overwrites it: ALIVE at the
        // end, drawn with a fade-out and never a death cap.
        int rax = lane_named(f, "rax");
        bool alive = false;
        for (const loom_span_t &s : f.spans)
            if (static_cast<int>(s.lane) == rax && s.t_write == 4)
                alive = s.t_end == kLoomAlive;
        check("df-chain: rax is alive at trace end", alive, "");
        loom_plan(f, wide(), &prims);
        bool rax_fade = false;
        for (const loom_prim_t &p : prims)
            if (p.kind == loom_prim::fade_out &&
                static_cast<int>(f.spans[p.a].lane) == rax)
                rax_fade = p.text == std::string(kLoomFadeOutText);
        check("df-chain: rax gets the fade-out", rax_fade, "");
        check("df-chain: no torn edge (the recording is complete)",
              count(prims, loom_prim::torn_edge) == 0, "");

        // The entry arguments are born of untraced state and carry real chips
        // (the producer's pre-instruction hook captured the source state).
        for (const char *n : {"rdi", "rsi"}) {
            int lane = lane_named(f, n);
            bool glyph = false;
            for (const loom_prim_t &p : prims)
                if (p.kind == loom_prim::born_untraced_glyph &&
                    static_cast<int>(f.spans[p.a].lane) == lane)
                    glyph = p.text == std::string(kLoomBornUntracedText);
            check(std::string("df-chain: ") + n +
                      " carries the born-untraced glyph",
                  glyph, loom_fabric_dump(f));
        }

        // The lineage the doc walks: (rax, 4) closes over {0,1,2,3,4}.
        loom_selection_t sel;
        check("df-chain: select (rax, 4)",
              loom_select(f, L.feed.edges.data(), L.feed.edges.size(),
                          static_cast<uint32_t>(rax), 4, &sel),
              "");
        check("df-chain: the closure is {0,1,2,3,4}",
              sel.steps == std::vector<uint32_t>({0, 1, 2, 3, 4}), "");
    }

    // ---------------------------------------------------------------------
    // loom-sum-via-rbx — walkthrough #2: a callee-save spill, an EFLAGS knot,
    // a restore. examples/flags.s:45.
    // ---------------------------------------------------------------------
    {
        Loaded L = load("loom-sum-via-rbx.asmtrace");
        if (!L.ok)
            return 1;
        const loom_fabric_t &f = L.fabric;
        const int band = band_lane(f);
        check("sum-via-rbx: the push made a stack band", band >= 0,
              loom_fabric_dump(f));
        check("sum-via-rbx: there is an EFLAGS lane",
              lane_named(f, "eflags") >= 0, loom_fabric_dump(f));
        int rbx = lane_named(f, "rbx");
        check("sum-via-rbx: rbx has a lane", rbx >= 0, "");

        // rbx's biography: the spill is a STORE to the stack band, and the
        // restore is a LOAD back into rbx.
        std::string all;
        for (const loom_span_t &s : f.spans) {
            if (static_cast<int>(s.lane) != band &&
                static_cast<int>(s.lane) != rbx)
                continue;
            uint32_t idx = static_cast<uint32_t>(&s - f.spans.data());
            for (const loom_bio_row_t &r : loom_biography(
                     f, L.feed.edges.data(), L.feed.edges.size(), idx))
                all += r.kind + ": " + r.text + "\n";
        }
        check("sum-via-rbx: the spill narrates as a store",
              all.find("store to mem[") != std::string::npos, all);
        check("sum-via-rbx: the restore narrates as a load into rbx",
              all.find("load into rbx") != std::string::npos, all);
        check("sum-via-rbx: the biography names the emulator tier",
              all.find("producer: emu-l0 — exact, replay") != std::string::npos,
              all);
    }

    // ---------------------------------------------------------------------
    // loom-truncated — the D7 dishonesty fixture (recs_cap = 4).
    // ---------------------------------------------------------------------
    {
        Loaded L = load("loom-truncated.asmtrace");
        if (!L.ok)
            return 1;
        const loom_fabric_t &f = L.fabric;
        check("truncated: the fabric knows it is truncated", f.prov.truncated,
              "the footer declared it and the fabric dropped the fact");
        loom_plan(f, wide(), &prims);
        auto torn = count(prims, loom_prim::torn_edge);
        check("truncated: exactly one torn edge", torn == 1,
              "got " + std::to_string(torn));
        for (const loom_prim_t &p : prims)
            if (p.kind == loom_prim::torn_edge) {
                // DOC DEVIATION (2026-07-24). 05-T2 specifies "trace truncated:
                // N of M steps recorded". v1 carries no dataflow step TOTAL —
                // the `end` footer has a truncated flag and nothing else — so a
                // replayed recording cannot supply M. Printing "6 of 6" would
                // claim the run ended where the buffer did. The banner names
                // the gap instead, and this assertion is the pin.
                check("truncated: the torn edge names the missing total",
                      p.text == "trace truncated: 6 steps recorded; this feed "
                                "did not record the total",
                      "text was: " + p.text);
                check("truncated: it never invents an M",
                      p.text.find(" of ") == std::string::npos,
                      "text was: " + p.text);
            }

        // The T2/T3 copy strings, over a real recording.
        check("truncated: the emulator recording carries the guest badge",
              count(prims, loom_prim::guest_badge) == 1, "");
        for (const loom_prim_t &p : prims)
            if (p.kind == loom_prim::guest_badge)
                check("truncated: the badge copy is verbatim",
                      p.text == "isolated guest — emulator replay, not silicon",
                      p.text);

        // rdi is read before anything writes it, so its worldline starts at
        // instrumentation and says so. rsi has NO lane here and that is the
        // fixture working: the operand buffer filled at 4 records, so the
        // producer never recorded the step-3 read of rsi. A truncated fabric
        // showing fewer lanes is a lower bound, not a claim that rsi was
        // untouched — which is exactly why the torn edge above is mandatory.
        check("truncated: rsi has no lane, because its records were dropped",
              lane_named(f, "rsi") < 0, loom_fabric_dump(f));
        {
            int lane = lane_named(f, "rdi");
            bool glyph = false;
            for (const loom_prim_t &p : prims)
                if (p.kind == loom_prim::born_untraced_glyph &&
                    static_cast<int>(f.spans[p.a].lane) == lane)
                    glyph = p.text == std::string(kLoomBornUntracedText);
            check("truncated: rdi carries the born-untraced glyph", glyph,
                  loom_fabric_dump(f));
        }

        // The audit is bounded, and says so in both places.
        check("truncated: the audit title states the bound",
              std::string(kLoomAuditTitle) ==
                  "zeroization audit — bounded to the traced window",
              kLoomAuditTitle);
        check("truncated: the audit hover states what 'clear' means",
              std::string(kLoomAuditHover)
                      .find("not overwritten within the traced window") !=
                  std::string::npos,
              kLoomAuditHover);
        // A truncated fabric's biography must call its rows a lower bound.
        if (!f.spans.empty()) {
            std::string all;
            for (const loom_bio_row_t &r :
                 loom_biography(f, L.feed.edges.data(), L.feed.edges.size(), 0))
                all += r.text + "\n";
            check("truncated: the biography says the rows are a lower bound",
                  all.find("lower bound") != std::string::npos, all);
        }
    }

    // ---------------------------------------------------------------------
    // loom-fork-demo — the base run of the fork differential (T7 step 4, whose
    // take legs live in the full-build test_loom_forks.cpp).
    // ---------------------------------------------------------------------
    {
        Loaded L = load("loom-fork-demo.asmtrace");
        if (!L.ok)
            return 1;
        const loom_fabric_t &f = L.fabric;
        check("fork-demo: 6 steps (arg 3 takes the jle arm)", f.steps == 6,
              "got " + std::to_string(f.steps));
        check("fork-demo: the last step is the ret at 0x13",
              f.insn_off.size() == 6 && f.insn_off[5] == 0x13,
              loom_fabric_dump(f));
        check(
            "fork-demo: step 1's shr wrote 0",
            [&] {
                for (const loom_span_t &s : f.spans)
                    if (s.t_write == 1 && f.lanes[s.lane].name == "rdx")
                        return s.value_valid && s.value == 0;
                return false;
            }(),
            loom_fabric_dump(f));
        check("fork-demo: there is an eflags lane (the cmp's knot)",
              lane_named(f, "eflags") >= 0, loom_fabric_dump(f));
    }

    // ---------------------------------------------------------------------
    // Determinism across the whole set.
    // ---------------------------------------------------------------------
    for (const char *n :
         {"loom-df-chain.asmtrace", "loom-sum-via-rbx.asmtrace",
          "loom-truncated.asmtrace", "loom-fork-demo.asmtrace"}) {
        Loaded a = load(n), b = load(n);
        check(std::string("two loads of ") + n + " weave identically",
              loom_fabric_dump(a.fabric) == loom_fabric_dump(b.fabric), "");
        std::vector<loom_prim_t> pa, pb;
        loom_plan(a.fabric, wide(), &pa);
        loom_plan(b.fabric, wide(), &pb);
        check(std::string("...and plan identically"),
              loom_plan_dump(pa) == loom_plan_dump(pb), "");
    }

    // A statistical recording from the corpus can never weave — the same law
    // as test_loom_fabric's synthetic case, over a file on disk.
    {
        std::string path =
            std::string(ASMTEST_GOLDEN_DIR) + "/export/survey-only.asmtrace";
        std::string err;
        auto rec = load_recording_file(path, err);
        if (!rec) {
            fail("load survey-only", err);
        } else {
            Streams s = decode_streams(*rec);
            loom_feed_t feed;
            loom_fabric_t f;
            std::string why;
            check("a survey-only recording never becomes fabric",
                  !loom_fabric_from_streams(s, &feed, &f, &why), "it wove");
            check("the refusal explains itself", !why.empty(), "");
        }
    }

    if (failures) {
        std::fprintf(stderr, "%d golden loom check(s) failed\n", failures);
        return 1;
    }
    std::printf("test_loom_golden: all checks passed\n");
    return 0;
}
