// test_motif_distinctness.cpp — the acceptance gate for the 3D axis budget
// (docs/superpowers/plans/2026-08-03-3d-scene-axis-budget.md T7b). A principled
// encoding that renders every program identically has failed, however
// principled it is, so this renders three recordings whose behaviour we already
// know and requires the frames to be pairwise DISTINCT.
//
// STEP 0 DECISION (do not re-open; the plan's T7b Step 0 has the argument):
//   All three recordings are GENERATED by `make asmtrace-golden` from
//   tools/asmtrace_record.c's record_scene_abs() byte arrays — a scalar integer
//   loop, a packed-XMM routine and a store-heavy routine — so the OpClass each
//   cell reports comes from the recording's own Capstone-recorded disasm text,
//   not from a fixture author. The byte arrays are still author-chosen: this
//   buys honest CLASSIFICATION of a real instruction stream, not an honest
//   program, and the claim here is scoped to that. asmtrace-golden-check holds
//   all three byte-stable in CI. Nothing here is hand-authored, so there is no
//   channel this test must refrain from asserting on.
//
//   Never capture live at test time. A distinctness gate over a
//   nondeterministic input CANNOT FAIL — run-to-run variation supplies the very
//   difference the gate looks for — which is strictly worse than the
//   self-confirming fixture the generated corpus exists to avoid.
//
//   The crossings channel is NOT gated here: its geometry comes from
//   views/build_crossing_layer, which this binary does not link, and its
//   fixture can only come from a live tracer. test_crossing pins it (T7c), in
//   a pure test.
//
// There is deliberately NO "the floor is >= 50% covered" assertion. What
// fraction of the VIEWPORT the floor covers is a camera-framing artefact, and
// the atlas does not raise the number of cells that carry data anyway — the
// packing claim is a cell-space property, proved in integers with no epsilon in
// test_projection.
#include <cstdio>
#include <string>

#include "gl_offscreen.h"
#include "image_distinct.h"

#ifndef ASMTEST_GOLDEN_DIR
#error "ASMTEST_GOLDEN_DIR must be defined by the build (mk/desktop.mk)"
#endif

using namespace asmdesk;
using namespace asmdesk::scene3d;
using namespace asmdesk::testing;

static int failures;
static void fail(const std::string &what, const std::string &why) {
    std::fprintf(stderr, "FAIL: %s (%s)\n", what.c_str(), why.c_str());
    failures++;
}
static void check(const std::string &what, bool cond, const std::string &why) {
    if (!cond)
        fail(what, why);
}

// Loads through the real loader, exactly as test_scene_fbo does.
static Recording load_scene(const char *name) {
    std::string err;
    auto rec =
        load_recording_file(std::string(ASMTEST_GOLDEN_DIR) + "/" + name, err);
    if (!rec) {
        fail(std::string("load ") + name, err);
        return Recording{};
    }
    return *rec;
}

int main() {
    // Three GENERATED recordings. Named for the WORK they do, not for a stream
    // they carry: `motif-stores` is store-heavy CODE, which is what the opcode
    // channel reads — it needs no `mem` stream, and a "motif-memcpy" name would
    // invite exactly that confusion.
    static const char *kScenes[3] = {"motif-scalar-loop.asmtrace",
                                     "motif-simd.asmtrace",
                                     "motif-stores.asmtrace"};

    // A missing recording is a FAILURE, never a skip — the same rule
    // test_scene_fbo already states for its golden scenes.
    for (const char *f : kScenes)
        check(std::string("scene is present: ") + f,
              scene_exists(ASMTEST_GOLDEN_DIR, f),
              "the acceptance gate cannot run without its inputs");

    std::string why;
    if (!gl_context_available(&why))
        // NOT a skip. The container pins software Mesa + EGL for exactly this,
        // and unlike test_scene_fbo there is no pure half to fall back on: the
        // picture IS the subject.
        fail("a GL context is obtainable",
             why + " — run this under `make docker-desktop`, which pins "
                   "libgl1-mesa-dri + libegl1-mesa-dev with "
                   "LIBGL_ALWAYS_SOFTWARE=1");

    if (failures == 0) {
        Scene scene;
        std::string serr;
        if (!scene.init_gl(&serr))
            fail("the scene shaders build", serr);
        ColorFbo cf;
        if (failures == 0 && !cf.create(160, 160))
            fail("the colour framebuffer is complete",
                 "incomplete FBO on this driver");
        const Camera cam; // the default three-quarter view, as shipped

        // `opcode` defaults OFF (it re-lifts the terrain rather than adding a
        // surface), so the gate sets it explicitly. `crossings` is deliberately
        // LEFT AT ITS DEFAULT and never asserted on: render_plane_scene uploads
        // no crossing geometry, so toggling it here would test nothing while
        // claiming a second channel.
        SceneLayers on;
        on.opcode = true;
        const auto kAtlas = space::Projection::Layout::Atlas;

        if (failures == 0) {
            Image shots[3];
            for (int i = 0; i < 3; i++) {
                const Recording rec = load_scene(kScenes[i]);
                shots[i] = render_plane_scene(scene, cf, cam, rec, on, kAtlas);
                check(std::string("the scene renders at all: ") + kScenes[i],
                      !image_blank(shots[i]),
                      "the frame came back at the clear colour");
            }
            for (int i = 0; i < 3; i++)
                for (int j = i + 1; j < 3; j++)
                    check(std::string("distinct: ") + kScenes[i] + " vs " +
                              kScenes[j],
                          images_distinct(shots[i], shots[j]),
                          "two programs with different behaviour rendered "
                          "alike — the encoding conveys nothing about what ran");

            // "Optional" has to mean the scene stands without the layer. Two
            // claims, and BOTH matter: the frame is still drawn, and it is
            // still a DIFFERENT frame, which is what makes the channel a
            // channel rather than decoration.
            SceneLayers off; // opcode already defaults false
            const Recording rec = load_scene(kScenes[0]);
            const Image bare =
                render_plane_scene(scene, cf, cam, rec, off, kAtlas);
            check("the scene still renders with the opcode channel off",
                  !image_blank(bare),
                  "turning the optional layer off emptied the viewport, at ink "
                  "fraction " +
                      std::to_string(image_ink_fraction(bare)));

            // This one is NOT judged against images_distinct's 2% bar, and the
            // reason is structural rather than a convenience. That bar is the
            // right question for "do two PROGRAMS look different", where step
            // counts move the whole terrain surface. The opcode tint re-colours
            // only the cells that hold CODE, and record_scene_abs caps a
            // routine at REC_WINDOW = 64 bytes, so those cells can never be
            // more than 64/4096 of the plane. 2% is unreachable BY
            // CONSTRUCTION here, and a gate that cannot pass however well the
            // encoding works measures the emitter, not the encoding.
            //
            // So the bar is the driver's OWN NOISE FLOOR, measured rather than
            // guessed: render the same scene twice with the same layers and
            // require the channel's effect to beat whatever that disagrees by.
            // No magic number to tune, and it tightens automatically on a
            // deterministic rasteriser (llvmpipe gives exactly 0).
            const Image bare_again =
                render_plane_scene(scene, cf, cam, rec, off, kAtlas);
            const float noise = image_diff_fraction(bare, bare_again);
            const float signal = image_diff_fraction(shots[0], bare);
            check("the renderer is deterministic enough to gate on", noise == 0.0f,
                  "two identical renders disagreed on " +
                      std::to_string(noise * 100.0f) +
                      "% of pixels, so no difference below that can be "
                      "attributed to a layer");
            check("the opcode channel actually changes the picture",
                  signal > noise,
                  "switching the channel on moved " +
                      std::to_string(signal * 100.0f) +
                      "% of pixels against a noise floor of " +
                      std::to_string(noise * 100.0f) +
                      "%; ZERO signal means it is drawing no information at "
                      "all (check set_opcode_terrain ran — without it the tint "
                      "samples an empty byte map)");
        }
    }

    if (failures) {
        std::fprintf(stderr, "%d motif check(s) failed\n", failures);
        return 1;
    }
    std::printf("test_motif_distinctness: all checks passed\n");
    return 0;
}
