#!/bin/sh
#
# scripts/amalgamate.sh — generate the single-header amalgamation
# asmtest_single.h from the public header and the C runtime. Track B of
# docs/plans/expansion-plan.md. Writes to stdout.
#
# The capture trampoline is assembly (src/capture.s) and cannot be inlined into
# a C header, so the amalgamation covers only the C surface; capture.s (or
# libasmtest.a) must still be linked. See the banner it emits and the README.

set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
hdr="$root/include/asmtest.h"
impl="$root/src/asmtest.c"
version=$(sed -n 's/^#define ASMTEST_VERSION "\(.*\)"/\1/p' "$hdr")

cat <<EOF
/*
 * asmtest_single.h — single-header amalgamation of the asm-test framework
 * (version $version). GENERATED by scripts/amalgamate.sh; do not edit by hand.
 *
 * Usage (STB-style): include this header for the API anywhere you need it. In
 * EXACTLY ONE translation unit, define ASMTEST_IMPLEMENTATION before including
 * it to emit the runner/runtime implementation:
 *
 *     #define ASMTEST_IMPLEMENTATION
 *     #include "asmtest_single.h"
 *
 * IMPORTANT: the register/flags capture trampoline is written in assembly
 * (src/capture.s) and CANNOT live in a C header. You must still assemble and
 * link that trampoline — or simply link libasmtest.a, which contains it. This
 * header covers only the C surface (assertions, runner, fixtures); the optional
 * emulator tier (asmtest_emu.h, libunicorn) is not included. For most projects
 * the static library (pkg-config asmtest) is the simpler path; see the README.
 */
#ifndef ASMTEST_SINGLE_H
#define ASMTEST_SINGLE_H

EOF

# Public API — drop the file's own include-guard lines; we supply our own.
sed -e '/^#ifndef ASMTEST_H$/d' \
    -e '/^#define ASMTEST_H$/d' \
    -e '\:^#endif /\* ASMTEST_H \*/$:d' "$hdr"

cat <<'EOF'

#endif /* ASMTEST_SINGLE_H */

/* ------------------------------------------------------------------------- */
/* Implementation — define ASMTEST_IMPLEMENTATION in exactly one TU.         */
/* ------------------------------------------------------------------------- */
#ifdef ASMTEST_IMPLEMENTATION
EOF

# Runtime — drop its include of the now-inlined public header.
sed -e '\:^#include "asmtest.h":d' "$impl"

cat <<'EOF'
#endif /* ASMTEST_IMPLEMENTATION */
EOF
