#!/bin/sh
# build-keystone.sh — build + install the Keystone assembler engine from source.
#
# Keystone (the assembler behind `make asm-test`) is not packaged by most Linux
# distros — `libkeystone-dev` does not exist on Ubuntu — so the in-line-asm tier
# builds it from a pinned source commit here. Idempotent: if pkg-config already
# finds keystone, it does nothing. Needs git, cmake, a C++ compiler, and make.
#
# Usage: scripts/build-keystone.sh [version]   (default version below)
#
# VERSION is a COMMIT, not a tagged release (60-arm32-riscv-author-mode.md T3):
# upstream's newest tag is 0.9.2 (Feb 2019), which has no RISC-V backend at all
# (no KS_ARCH_RISCV in its header). RISC-V support landed on the unreleased
# default branch afterward and was never cut into a tag, so this pin follows
# the same "git-commit, not a mutable tag" mechanism scripts/fetch-libdft.sh /
# scripts/build-dynamorio-macos.sh already use for their own untagged pins — a
# short-sha "version" key into the digest manifest, fetched by SHA rather than
# `git clone --branch` (which only accepts a real ref, not an arbitrary commit).
set -eu

VERSION="${1:-0d9567f08c0c}"
PREFIX="${KEYSTONE_PREFIX:-/usr/local}"
prog=$(basename "$0")
. "$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/lib-thirdparty.sh"

# Already present? (the in-tree builds find it via pkg-config.)
if command -v pkg-config >/dev/null 2>&1 && pkg-config --exists keystone 2>/dev/null; then
    echo "$prog: keystone already installed ($(pkg-config --modversion keystone)), skipping"
    exit 0
fi

# sudo only when not root and available (CI runners are non-root with sudo).
SUDO=""
[ "$(id -u)" -ne 0 ] && command -v sudo >/dev/null 2>&1 && SUDO="sudo"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

echo "$prog: building keystone $VERSION -> $PREFIX"
# Integrity pin (B5): assert the fetched commit matches the pinned one before
# building anything from it. want the digest manifest's "commit:<full-sha>" —
# regenerated by scripts/refresh-thirdparty-digests.sh, which resolves this
# short-sha "version" the same way it already resolves dynamorio-fork's
# (GitHub's commits API, not a tag lookup — this VERSION is not a tag).
want=$(tp_digest git-commit keystone "$VERSION") || {
    echo "$prog: ERROR: no pinned commit for keystone $VERSION in the digest manifest" >&2
    echo "$prog:        regenerate it with scripts/refresh-thirdparty-digests.sh" >&2
    exit 1
}
commit="${want#commit:}"
# Fetch-by-SHA (GitHub serves a shallow fetch of any reachable commit, not
# just a named ref), with a full-clone fallback for a host/mirror that
# refuses it — scripts/fetch-libdft.sh's exact shape, generalized here so
# this same clone works whether VERSION is a commit (today) or a tag (if a
# future bump lands on a real release again).
if git init -q "$work/keystone" \
   && git -C "$work/keystone" remote add origin https://github.com/keystone-engine/keystone.git \
   && git -C "$work/keystone" fetch -q --depth 1 origin "$VERSION" \
   && git -C "$work/keystone" checkout -q --detach FETCH_HEAD; then
    :
else
    echo "$prog: fetch-by-SHA unavailable; falling back to full clone" >&2
    rm -rf "$work/keystone"
    git clone -q https://github.com/keystone-engine/keystone.git "$work/keystone"
    git -C "$work/keystone" checkout -q --detach "$VERSION"
fi
got=$(cd "$work/keystone" && git rev-parse HEAD)
if [ "$got" != "$commit" ]; then
    echo "$prog: ERROR: keystone $VERSION resolved to $got, expected pinned $commit (moved ref?)" >&2
    exit 1
fi

# --- make the pinned tree configurable by a modern CMake ---------------------
# Both edits are applied AFTER the commit assertion above, which is what keeps
# the B5 pin meaningful: integrity is proven against unmodified upstream first,
# and every change we then make is visible in this file rather than baked into
# a vendored tarball. The pinned commit (T3) already bumped
# cmake_minimum_required to 3.10 and dropped the CMP0051 OLD policy set
# entirely (upstream's own CMake4/GCC15 compatibility fix, landed the same
# month as this pin), so both patches below are expected to no-op here — kept
# rather than deleted so a future re-pin onto an OLDER commit (e.g. bisecting
# a regression) still configures cleanly without rediscovering this fix.
#
# Two CMakeLists used to set `cmake_policy(SET CMP0051 OLD)`. CMake 4 removed
# OLD for that policy outright — unlike the minimum-version check, NO flag
# re-enables it, so configure fails hard. CMP0051 NEW only means generator
# expressions appear in a target's SOURCES property; keystone's build never
# reads SOURCES, so the switch is inert for this tree. sed writes through a
# temp file rather than using `sed -i`, whose in-place spelling differs
# between GNU and BSD/macOS sed.
for f in CMakeLists.txt llvm/CMakeLists.txt; do
    [ -f "$work/keystone/$f" ] || continue
    if grep -q 'cmake_policy(SET CMP0051 OLD)' "$work/keystone/$f"; then
        sed 's/cmake_policy(SET CMP0051 OLD)/cmake_policy(SET CMP0051 NEW)/' \
            "$work/keystone/$f" > "$work/keystone/$f.tmp"
        mv "$work/keystone/$f.tmp" "$work/keystone/$f"
        echo "$prog: patched $f — CMP0051 OLD -> NEW (CMake 4 removed OLD)"
    fi
done

mkdir -p "$work/keystone/build"
cd "$work/keystone/build"

# Keystone bundles an LLVM fork that predates GCC 13's stricter header
# transitivity: llvm/include/llvm/ADT/STLExtras.h uses intptr_t without including
# <cstdint>, which used to arrive indirectly and no longer does (GCC 13+ fails
# with "'intptr_t' has not been declared"). Force-including the header supplies
# it without touching the sources; it is a standard C++11 header, so this is a
# no-op on the older toolchains that compiled the tree unaided.
KS_CXXFLAGS="-include cstdint ${CXXFLAGS:-}"

# Darwin: CMake's default gives the dylib an `@rpath/libkeystone.N.dylib` install
# name, so every consumer linked with a plain `-L$PREFIX/lib -lkeystone` (the
# flags the tree uses) aborts at load with "no LC_RPATH's found". Bake the
# absolute install-name directory instead — the way Homebrew ships dylibs — so
# plain links work. A no-op on non-Apple platforms. Same fix, same reason, as
# build-capstone.sh; the two source builds must not diverge here.
#
# $(tp_cmake_compat) is intentionally unquoted: it expands to one argument on a
# cmake >= 3.31 (whose 4.x releases reject this pinned tree's
# cmake_minimum_required) and to nothing at all on older ones.
cmake $(tp_cmake_compat) \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SHARED_LIBS=ON \
      -DLLVM_TARGETS_TO_BUILD="AArch64;ARM;X86;RISCV" \
      -DCMAKE_INSTALL_PREFIX="$PREFIX" \
      -DCMAKE_INSTALL_NAME_DIR="$PREFIX/lib" \
      -DCMAKE_CXX_FLAGS="$KS_CXXFLAGS" \
      ..
make "-j$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 2)"
$SUDO make install

# Record the license at the exact version built, so packaging can vendor a
# version-matched THIRD-PARTY-LICENSES notice (mirrors build-capstone.sh).
licdir="$PREFIX/share/licenses/keystone-$VERSION"
$SUDO mkdir -p "$licdir"
for f in COPYING COPYING.LIB LICENSE.TXT EXCEPTIONS-CLIENT; do
    [ -f "$work/keystone/$f" ] && $SUDO cp "$work/keystone/$f" "$licdir/"
done

# K1 (CI cache): record the exact installed file set — cmake's install manifest
# plus the license dir — so scripts/thirdparty-cache.sh can tar precisely these
# files into a CI cache and restore them next run. No-op unless the caller sets
# ASMTEST_TP_MANIFEST_DIR (CI does; local builds don't need it).
if [ -n "${ASMTEST_TP_MANIFEST_DIR:-}" ]; then
    mkdir -p "$ASMTEST_TP_MANIFEST_DIR"
    { cat install_manifest.txt; echo; find "$licdir" -type f 2>/dev/null; } \
        | sed '/^[[:space:]]*$/d' > "$ASMTEST_TP_MANIFEST_DIR/keystone-$VERSION.list"
fi

# Refresh the loader cache so the freshly installed lib is found (Linux).
command -v ldconfig >/dev/null 2>&1 && $SUDO ldconfig || true

echo "$prog: done"
