#!/usr/bin/env python3
# gen-terms.py — generate the desktop GUI's in-app term registry from the ONE
# Sphinx glossary (docs/project/glossary.md), so the app's words and the docs'
# words cannot drift (24-one-visual-language.md T3). Mirrors the dt_nav_bindings
# -> help pattern (one table, two consumers), applied to words.
#
#   scripts/gen-terms.py docs/project/glossary.md > terms_generated.h
#
# The output is a plain C header: a `dt_term_entry` array the registry TU
# (desktop/src/ui/terms.cpp) #includes. No dependency but the stdlib.
import re
import sys


def clean(text: str) -> str:
    """Reduce MyST/Markdown to plain tooltip text."""
    # {term}`Foo <bar>` / {term}`Foo` -> Foo ; other roles likewise.
    text = re.sub(r"\{[a-z]+\}`([^`<]*?)\s*<[^`>]*>`", r"\1", text)
    text = re.sub(r"\{[a-z]+\}`([^`]*)`", r"\1", text)
    # [label](url) -> label
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = text.replace("`", "")
    # *emph* / **strong** markers -> plain
    text = re.sub(r"\*+([^*]+)\*+", r"\1", text)
    return re.sub(r"\s+", " ", text).strip()


def escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def parse(path: str):
    entries = []
    in_block = False
    pending = []   # headwords awaiting their shared definition
    defbuf = []
    with open(path, encoding="utf-8") as f:
        lines = f.readlines()
    for raw in lines:
        line = raw.rstrip("\n")
        if not in_block:
            if line.strip().startswith(":::{glossary}"):
                in_block = True
            continue
        if line.strip() == ":::":
            break
        if line.strip().startswith(":") and not line.startswith(" "):
            continue  # directive option, e.g. :sorted:
        if line == "":
            if pending and defbuf:
                d = clean(" ".join(defbuf))
                for t in pending:
                    entries.append((t, d))
                pending, defbuf = [], []
            continue
        if line.startswith(" ") or line.startswith("\t"):
            defbuf.append(line.strip())      # definition line
        else:
            if defbuf:                       # a new headword after a definition
                d = clean(" ".join(defbuf))
                for t in pending:
                    entries.append((t, d))
                pending, defbuf = [], []
            pending.append(line.strip())     # a (possibly grouped) headword
    if pending and defbuf:
        d = clean(" ".join(defbuf))
        for t in pending:
            entries.append((t, d))
    return entries


def main() -> int:
    if len(sys.argv) != 2:
        sys.stderr.write("usage: gen-terms.py <glossary.md>\n")
        return 2
    entries = parse(sys.argv[1])
    out = sys.stdout
    out.write("// GENERATED by scripts/gen-terms.py from docs/project/"
              "glossary.md — do not edit.\n")
    out.write("// The desktop GUI term registry (24-one-visual-language.md T3):"
              " ONE source, the glossary.\n")
    out.write("#ifndef ASMDESK_UI_TERMS_GENERATED_H\n")
    out.write("#define ASMDESK_UI_TERMS_GENERATED_H\n")
    out.write("struct dt_term_entry { const char *term; const char *def; };\n")
    out.write("static const dt_term_entry k_dt_terms[] = {\n")
    for term, d in entries:
        out.write('    {"%s", "%s"},\n' % (escape(term), escape(d)))
    out.write("};\n")
    out.write("static const int k_dt_terms_n = %d;\n" % len(entries))
    out.write("#endif\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
